export const pokemonTypes = [
  { normal: {} },
  { fire: {} },
  {
    bug: {
      normal: 1,
      fire: 0.5,
      water: 1,
      electric: 1,
      grass: 2,
      ice: 1,
      fighting: 0.5,
      poison: 0.5,
      ground: 1,
      flying: 0.5,
      psychic: 2,
      bug: 1,
      rock: 1,
      ghost: 0.5,
      dragon: 1,
      dark: 1,
      steel: 0.5,
    },
  },
  {
    rock: {
      normal: 1,
      fire: 2,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 2,
      fighting: 0.5,
      poison: 1,
      ground: 0.5,
      flying: 2,
      psychic: 1,
      bug: 2,
      rock: 1,
      ghost: 1,
      dragon: 1,
      dark: 1,
      steel: 0.5,
    },
  },
  {
    ghost: {
      normal: 2,
      fire: 1,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 1,
      fighting: 1,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 2,
      bug: 1,
      rock: 1,
      ghost: 2,
      dragon: 1,
      dark: 0.5,
      steel: 0.5,
    },
  },
  {
    dragon: {
      normal: 1,
      fire: 1,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 1,
      fighting: 1,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 1,
      bug: 1,
      rock: 1,
      ghost: 1,
      dragon: 2,
      dark: 1,
      steel: 0.5,
    },
  },
  {
    dark: {
      normal: 1,
      fire: 1,
      water: 1,
      electric: 1,
      grass: 1,
      ice: 1,
      fighting: 0.5,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 2,
      bug: 1,
      rock: 1,
      ghost: 2,
      dragon: 1,
      dark: 0.5,
      steel: 0.5,
    },
  },
  {
    steel: {
      normal: 1,
      fire: 0.5,
      water: 0.5,
      electric: 0.5,
      grass: 1,
      ice: 2,
      fighting: 1,
      poison: 1,
      ground: 1,
      flying: 1,
      psychic: 1,
      bug: 1,
      rock: 2,
      ghost: 1,
      dragon: 1,
      dark: 1,
      steel: 0.5,
    },
  },
];
